name: Test Database Migrations

on:
  push:
    paths:
      - "app/db/**"
      - "app/operation/**"
      - "tests/**"
      - "app/routers/**"
  pull_request:
    paths:
      - "app/db/**"
      - "app/operation/**"
      - "tests/**"
      - "app/routers/**"

jobs:
  test-databases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db:
          - name: postgresql
            image: postgres:latest
            env:
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: testdb
            port: 5432
            url: postgresql+asyncpg://postgres:postgres@localhost:5432/testdb
            health_cmd: pg_isready
          - name: mysql
            image: mysql:latest
            env:
              MYSQL_ROOT_PASSWORD: root
              MYSQL_DATABASE: testdb
            port: 3306
            url: mysql+asyncmy://root:root@localhost:3306/testdb
            health_cmd: mysqladmin ping -hlocalhost -uroot -proot
          - name: sqlite
            url: sqlite+aiosqlite:///./test.db

    services:
      db:
        image: ${{ matrix.db.image }}
        env: ${{ toJson(matrix.db.env) }}
        ports:
          - ${{ matrix.db.port }}:${{ matrix.db.port }}
        options: >-
          --health-cmd="${{ matrix.db.health_cmd }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: make setup

      - name: Run Alembic Migrations
        env:
          SQLALCHEMY_DATABASE_URL: ${{ matrix.db.url }}
          TEST_FROM: github
        run: make run-migration

      - name: Run Tests
        run: make test
