name: Test Database Migrations

on:
  push:
    paths:
      - "app/db/**"
      - "app/operation/**"
      - "tests/**"
      - "app/routers/**"
  pull_request:
    paths:
      - "app/db/**"
      - "app/operation/**"
      - "tests/**"
      - "app/routers/**"

jobs:
  test-postgresql:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest # Use the latest version of PostgreSQL
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: make setup

      # - name: Wait for PostgreSQL to be ready
      # run: sleep 10

      - name: Run Alembic Migrations
        env:
          SQLALCHEMY_DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/testdb
          TEST_FROM: github
        run: make run-migration

      - name: Run Tests
        run: make test

  test-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest # Use the latest version of MySQL
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -hlocalhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: make setup
      # - name: Wait for MySQL to be ready
      #   run: sleep 10

      - name: Run Alembic Migrations
        env:
          SQLALCHEMY_DATABASE_URL: mysql+asyncmy://root:root@localhost:3306/testdb
          TEST_FROM: github
        run: make run-migration

      - name: Run Tests
        run: make test

  test-sqlite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: make setup

      - name: Run Alembic Migrations
        env:
          SQLALCHEMY_DATABASE_URL: sqlite+aiosqlite:///./test.db
          TEST_FROM: github
        run: make run-migration

      - name: Run Tests
        run: make test
